namespace SpriteKind {
    export const Collectable = SpriteKind.create()
}
scene.onHitWall(SpriteKind.Player, function (sprite, location) {
    if (PLAYERSPRITE.tileKindAt(TileDirection.Bottom, grafxkid.blueBrickBlockAlt)) {
        music.jumpUp.play()
        PLAYERSPRITE.vy = -150
    } else if (PLAYERSPRITE.tileKindAt(TileDirection.Bottom, sprites.dungeon.darkGroundCenter)) {
        music.thump.play()
        LOL_CHANGE_TIME_LOC = location
        LOL_CHANGE_TIME = 1
    } else {
    	
    }
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile`, function (sprite, location) {
    music.beamUp.play()
    tiles.setTileAt(location, assets.tile`transparency16`)
    LAST_CHECKPOINT = location
    COLLECT_BEAM = sprites.create(img`
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ......f2f.......
        ................
        ................
        ................
        `, SpriteKind.Collectable)
    COLLECTABLESPRITE = sprites.create(assets.tile`myTile`, SpriteKind.Collectable)
    tiles.placeOnTile(COLLECTABLESPRITE, location)
    tiles.placeOnTile(COLLECT_BEAM, location)
    COLLECT_BEAM.setFlag(SpriteFlag.GhostThroughTiles, true)
    COLLECT_BEAM_TIME = 1
    animation.runImageAnimation(
    COLLECTABLESPRITE,
    [img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . b . . . . . . . 
        . . . . . . . b d b . . . . . . 
        . . . . . . . c d c . . . . . . 
        . . . . . . . c a c . . . . . . 
        . . . . . . c d a d c . . . . . 
        . . . b c c d a a a d c c b . . 
        . . b d d a a a a a a a d d b . 
        . . . b c c d a a a d c c b . . 
        . . . . . . c d a d c . . . . . 
        . . . . . . . c a c . . . . . . 
        . . . . . . . c d c . . . . . . 
        . . . . . . . b d b . . . . . . 
        . . . . . . . . b . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . b d b . . . . . . 
        . . . . . . . b d b c . . . . . 
        . . . . b b c a a a c b b . . . 
        . . . . b a a a 1 a a a b . . . 
        . . . c c a a a 1 a a a c c . . 
        . . b b a a a 1 1 1 a a a b b . 
        . . d d a 1 1 1 1 1 1 1 a d d . 
        . . b b a a a 1 1 1 a a a b b . 
        . . . c c a a a 1 a a a c c . . 
        . . . . b a a a 1 a a a b . . . 
        . . . . b b c a a a c b b . . . 
        . . . . . . c b d b c . . . . . 
        . . . . . . . b d b . . . . . . 
        . . . . . . . . . . . . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . f . . . . . . . . . . 
        . . f f . . . f f f . . . . . . 
        . . f f . f f f f f f f . . . . 
        . . . . f f f f f f f f f . . . 
        . . . f f f f f f f f f f f . . 
        . . . f f f f f f f f f f f . . 
        . . f f f f f f f f f f f f f . 
        . . f f f f f f f f f f f f f . 
        . . f f f f f f f f f f f f f . 
        . . . f f f f f f f f f f f . . 
        . . . f f f f f f f f f f f . . 
        . . . . f f f f f f f f f . . . 
        . . f . . f f f f f f f . . . . 
        . . . . . . . f f f . . . . f . 
        . . . . . . . . . . . . . . . . 
        `],
    100,
    true
    )
    info.changeScoreBy(1)
    info.changeLifeBy(1)
})
scene.onOverlapTile(SpriteKind.Player, grafxkid.brickBlock, function (sprite, location) {
    music.bigCrash.play()
    for (let value of tiles.getTilesByType(assets.tile`myTile13`)) {
        tiles.setTileAt(value, grafxkid.blueBrickBlock)
        tiles.setWallAt(value, true)
    }
    tiles.placeOnTile(PLAYERSPRITE, LAST_CHECKPOINT)
})
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    Projectil = sprites.create(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . 4 4 . . . . . . . 
        . . . . . . 4 5 5 4 . . . . . . 
        . . . . . . 2 5 5 2 . . . . . . 
        . . . . . . . 2 2 . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, SpriteKind.Projectile)
    Projectil.follow(Enemy2)
    projectile = sprites.createProjectileFromSprite(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . 4 4 . . . . . . . 
        . . . . . . 4 5 5 4 . . . . . . 
        . . . . . . 2 5 5 2 . . . . . . 
        . . . . . . . 2 2 . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, PLAYERSPRITE, 100, 0)
})
controller.up.onEvent(ControllerButtonEvent.Pressed, function () {
    if (PLAYERSPRITE.isHittingTile(CollisionDirection.Bottom)) {
        PLAYERSPRITE.vy = -75
    }
})
sprites.onOverlap(SpriteKind.Enemy, SpriteKind.Player, function (sprite, otherSprite) {
    info.changeLifeBy(-1)
    sprites.destroy(sprite)
})
info.onLifeZero(function () {
	
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Food, function (sprite, otherSprite) {
    info.changeLifeBy(1)
    sprites.destroy(sprite)
})
scene.onOverlapTile(SpriteKind.Player, grafxkid.iceCubeBlock, function (sprite, location) {
    controller.moveSprite(PLAYERSPRITE, 0, 0)
    WIN = 1
})
sprites.onOverlap(SpriteKind.Projectile, SpriteKind.Enemy, function (sprite, otherSprite) {
    sprites.destroy(otherSprite)
})
let WIN = 0
let projectile: Sprite = null
let Projectil: Sprite = null
let COLLECT_BEAM_TIME = 0
let COLLECTABLESPRITE: Sprite = null
let COLLECT_BEAM: Sprite = null
let LOL_CHANGE_TIME = 0
let LOL_CHANGE_TIME_LOC: tiles.Location = null
let Enemy2: Sprite = null
let LAST_CHECKPOINT: tiles.Location = null
let PLAYERSPRITE: Sprite = null
let foodd: Sprite = null
scene.setBackgroundColor(15)
for (let valeur of tiles.getTilesByType(assets.tile`myTile14`)) {
    foodd = sprites.create(img`
        ..........bbbbbb................
        .......bbb444444bb..............
        .....2244444ddd444b.............
        ....244444444dddd44e............
        ...244444444444ddd4be...........
        ..244444444444444d44be..........
        .2b444444444444444d4be..........
        .2b44444444444444444bbe.........
        2bbb4444444444444444bbe.........
        2bbb4444444444444444bbe.........
        2bb4b4444444444444444bbe........
        2bb4444444444444444444be........
        2bb44444444444444444444e........
        2bbb444bbb4444444444444e........
        22bbb444bb4bb444444444be........
        .2bbbbb44bbbb44444444bbe........
        .22bbbbbbbb44bbb444444bbe.......
        ..eeebbbbbbb44bbb444444be.......
        ...eeeeebbbbbbbb44b4444be.......
        .....eeeeee222bb44bbb4bbe.......
        .......eeeee222bb44bbbbee.......
        ............e222bbbbbbbec.......
        ..............ee2bbbbeebdb......
        .................eeeeecdddb.....
        .......................cd11bbbb.
        ........................cd111dbb
        .........................b11111c
        .........................c11dd1c
        .........................cd1dbc.
        .........................cb11c..
        ..........................ccc...
        ................................
        `, SpriteKind.Food)
    tiles.placeOnTile(foodd, valeur)
    tiles.setTileAt(valeur, assets.tile`transparency16`)
}
PLAYERSPRITE = sprites.create(img`
    . . . . . . f f f f . . . . . . 
    . . . . f f f 2 2 f f f . . . . 
    . . . f f f 2 2 2 2 f f f . . . 
    . . f f f e e e e e e f f f . . 
    . . f f e 2 2 2 2 2 2 e e f . . 
    . . f e 2 f f f f f f 2 e f . . 
    . . f f f f e e e e f f f f . . 
    . f f e f b f 4 4 f b f e f f . 
    . f e e 4 1 f d d f 1 4 e e f . 
    . . f e e d d d d d d e e f . . 
    . . . f e e 4 4 4 4 e e f . . . 
    . . e 4 f 2 2 2 2 2 2 f 4 e . . 
    . . 4 d f 2 2 2 2 2 2 f d 4 . . 
    . . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
    . . . . . f f f f f f . . . . . 
    . . . . . f f . . f f . . . . . 
    `, SpriteKind.Player)
info.setLife(3)
scene.cameraFollowSprite(PLAYERSPRITE)
controller.moveSprite(PLAYERSPRITE, 50, 0)
tiles.setTilemap(tilemap`level1`)
LAST_CHECKPOINT = tiles.getTileLocation(0, 10)
tiles.placeOnTile(PLAYERSPRITE, LAST_CHECKPOINT)
for (let index = 0; index < 10; index++) {
    tiles.placeOnRandomTile(Enemy2, assets.tile`myTile21`)
    Enemy2 = sprites.create(img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f1111111df.......
        ......fd1111111ddf......
        ......fd111111dddf......
        ......fd111ddddddf......
        ......fd1dfbddddbf......
        ......fbddfcdbbbcf......
        .......f11111bbcf.......
        .......f1b1fffff........
        .......fbfc111bf........
        ........ff1b1bff........
        .........fbfbfff.f......
        ..........ffffffff......
        ............fffff.......
        ........................
        ........................
        ........................
        ........................
        `, SpriteKind.Enemy)
    Enemy2.follow(PLAYERSPRITE)
    Enemy2.setVelocity(-50, -90)
}
forever(function () {
    if (WIN == 1) {
        WIN = 0
        PLAYERSPRITE.x += 16
        tiles.placeOnTile(PLAYERSPRITE, tiles.getTileLocation(228, 12))
    }
})
forever(function () {
    PLAYERSPRITE.vy += 2
})
forever(function () {
    if (LOL_CHANGE_TIME == 1) {
        LOL_CHANGE_TIME = 0
        pause(200)
        tiles.setTileAt(LOL_CHANGE_TIME_LOC, assets.tile`myTile13`)
        tiles.setWallAt(LOL_CHANGE_TIME_LOC, false)
    }
})
forever(function () {
    if (COLLECT_BEAM_TIME == 1) {
        COLLECT_BEAM_TIME = 0
        pause(2000)
        COLLECT_BEAM.destroy()
    }
})
forever(function () {
    controller.moveSprite(PLAYERSPRITE, 50, 0)
})
